---
- name: Start Java service with nohup
  hosts: all
  become: yes
  tasks:
    - name: Start the Java service in background
      command: nohup /usr/lib/jvm/jdk1.8.0_181/bin/java -jar -Dspring.profiles.active=test /home/ca_ybakir/wallet.jar --server.port=9281 > /home/ca_ybakir/wallet.log 2>&1 &
      async: 1
      poll: 0

    - name: Ensure the service is running
      shell: "ps aux | grep wallet.jar | grep -v grep"
      register: result
      ignore_errors: yes

    - name: Display if the Java service is running
      debug:
        var: result.stdout
