---
- name: 10.135.30.12-Wallet-9281
  hosts: all
  become: yes
  tasks:
    - name: 10.135.30.12-Wallet-9281
      command: sudo nohup /usr/lib/jvm/jdk1.8.0_181/bin/java -jar -Dspring.profiles.active=test /home/ca_ybakir/wallet.jar --server.port=9281 > /home/ca_ybakir/wallet.log 2>&1 &
      register: display_output

    - name: display_output
      debug:
        var: display_output.stdout_lines

    - name: save-disk-usage-output-to-file-with-timestamp
      copy:
        content: "{{ display_output.stdout }}"
        dest: "/tmp/awx_task_{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}.log"
