---
- name: Curl Test
  hosts: all
  become: yes
  tasks:
    - name: Test Curl
      shell: curl https://vposv2.moneypay.internal
      #register: execute_output
      ignore_errors: yes
      register: display_output

    - name: display_output
      debug:
        var: display_output.stdout_lines
  
