---
- name: check-disk-usage
  hosts: all
  become: yes
  tasks:
    - name: check-disk-usage
      command: lsblk
      register: display_output

    - name: display_output
      debug:
        var: display_output.stdout_lines

    - name: save-disk-usage-output-to-file-with-timestamp
      copy:
        content: "{{ display_output.stdout }}"
        dest: "/tmp/awx_{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}.txt"
