---
- name: check-disk-usage
  hosts: all
  become: yes
  tasks:
    - name: check-disk-usage
      command: lsblk
      register: display_output
    - name: display_output
      debug:
        var: display_output.stdout_lines
