---
- name: Download file via SFTP
  hosts: all
  become: yes
  vars:
    sftp_user: "ansible"
    sftp_host: "10.0.102.22"
    sftp_password: "Volcano7854"

  tasks:
    - name: Download file using SFTP
      shell: |
        echo -e "open sftp://{{ sftp_user }}:{{ sftp_password }}@{{ sftp_host }}\nget UEMS_LinuxAgent.bin /tmp/\nbye" | sftp -b -
      register: sftp_output
      ignore_errors: yes

    - name: Display SFTP output
      debug:
        var: sftp_output.stdout_lines
