---
- name: check-etc-hosts
  hosts: all
  become: yes
  tasks:
    - name: check-etc-hosts
      shell: "more /etc/hosts"
      register: display_output

    - name: display_output
      debug:
        var: display_output.stdout_lines

    - name: save-check-etc-hosts-output-to-file-with-timestamp
      copy:
        content: "{{ display_output.stdout }}"
        dest: "/tmp/awx_task_{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}.log"
