---
- name: Deploy UEMS Linux Agent
  hosts: all
  become: yes
  tasks:
    - name: Copy file from SFTP server
      shell: |
        echo | sftp 10.0.102.22:/* /tmp
      register: sftp_output
      ignore_errors: yes

    - name: Display SFTP output
      debug:
        var: sftp_output.stdout_lines

    - name: Change directory to /tmp
      shell: cd /tmp
      args:
        chdir: /tmp

    - name: Make the binary executable
      file:
        path: /tmp/UEMS_LinuxAgent.bin
        mode: '0755'
        state: file

    - name: Execute UEMS Linux Agent binary
      shell: ./UEMS_LinuxAgent.bin
      args:
        chdir: /tmp
      register: execute_output
      ignore_errors: yes

    - name: Display execution output
      debug:
        var: execute_output.stdout_lines
