---
- name: Deploy Node Exporter Tar.gz
  hosts: all
  become: yes
  tasks:
    - name: Create folder
      shell: sudo mkdir -p /app/node_exporter/
      register: execute_output
      ignore_errors: yes
