---
- name: Deploy Pipeline SSH Key
  hosts: all
  become: yes
  tasks:
    - name: move id_rsa.pub
      shell: cat /home/ca_pipeline/.ssh/id_rsa.pub >> /home/ca_pipeline/.ssh/authorized_keys
      register: download_readme_output
  
