---
- name: Deploy UEMS Linux Agent
  hosts: all
  become: yes
  vars:
    sftp_user: "ansible"
    sftp_host: "10.0.102.22"
    sftp_password: "Volcano7854"

  tasks:
    - name: Create SFTP batch file
      copy:
        dest: /tmp/sftp_batch.txt
        content: |
          open {{ sftp_user }}@{{ sftp_host }}
          get UEMS_LinuxAgent.bin /tmp/
          bye

    - name: Copy file from SFTP server
      shell: echo "{{ sftp_password }}" | sftp -o BatchMode=no -b /tmp/sftp_batch.txt
      register: sftp_output
      ignore_errors: yes

    - name: Display SFTP output
      debug:
        var: sftp_output.stdout_lines

    - name: Execute UEMS Linux Agent binary
      shell: ./UEMS_LinuxAgent.bin
      args:
        chdir: /tmp
      register: execute_output
      ignore_errors: yes

    - name: Display execution output
      debug:
        var: execute_output.stdout_lines
