---
- name: Deploy UEMS Linux Agent with SFTP
  hosts: all
  become: yes
  vars:
    sftp_user: "ansible"
    sftp_host: "10.0.102.22"
    sftp_password: "Volcano7854"  # SFTP kullanıcısının parolası burada belirtiliyor.

  tasks:
    - name: Copy files from SFTP server to /tmp
      expect:
        command: sftp -o StrictHostKeyChecking=no {{ sftp_user }}@{{ sftp_host }}:/* /tmp
        responses:
          "password:": "{{ sftp_password }}"
      register: sftp_output
      ignore_errors: yes

    - name: Display SFTP output
      debug:
        var: sftp_output.stdout_lines

    - name: Make the binary executable
      file:
        path: /tmp/UEMS_LinuxAgent.bin
        mode: '0755'
        state: file

    - name: Execute UEMS Linux Agent binary
      shell: ./UEMS_LinuxAgent.bin
      args:
        chdir: /tmp
      register: execute_output
      ignore_errors: yes

    - name: Display execution output
      debug:
        var: execute_output.stdout_lines
