---
- name: Deploy UEMS Linux Agent with SFTP
  hosts: all
  become: yes
  vars:
    sftp_user: "ansible"
    sftp_host: "10.0.102.22"
    sftp_password: "Volcano7854"

  tasks:
    - name: Create SFTP batch file
      copy:
        content: |
          open sftp://{{ sftp_user }}:{{ sftp_password }}@{{ sftp_host }}
          mget * /tmp/
          bye
        dest: /tmp/sftp_batch.txt

    - name: Run SFTP batch
      shell: sftp -b /tmp/sftp_batch.txt
      register: sftp_output
      ignore_errors: yes

    - name: Display SFTP output
      debug:
        var: sftp_output.stdout_lines

    - name: Make the binary executable
      file:
        path: /tmp/UEMS_LinuxAgent.bin
        mode: '0755'
        state: file

    - name: Execute UEMS Linux Agent binary
      shell: ./UEMS_LinuxAgent.bin
      args:
        chdir: /tmp
      register: execute_output
      ignore_errors: yes

    - name: Display execution output
      debug:
        var: execute_output.stdout_lines
