---
- name: Java trust store'a Moneypay Internal v2 sertifikasını ekle
  hosts: all
  become: yes
  vars:
    cert_file: "/tmp/moneypay-internal-2025-v2.crt"
    cert_alias: "moneypay_internal_crt_v2"
    keystore_pass: "changeit"
    keytool_bin: "/usr/bin/keytool"
    ks_java17: "/usr/lib/jvm/java-17-openjdk-amd64/lib/security/cacerts"
    ks_java8:  "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts"

  tasks:

    - name: Delete Old Temp Cert
      shell: sudo rm -rf /tmp/moneypay-internal-2025-v2.crt
      register: execute_output
      ignore_errors: yes
      
    - name: Download id_rsa
      shell: wget http://10.0.102.22/moneypay-internal-2025-v2.crt -O /tmp/moneypay-internal-2025-v2.crt
      register: download_readme_output
      
    - name: keytool var mı?
      stat:
        path: "{{ keytool_bin }}"
      register: keytool_stat

    - name: keytool yoksa hata ver
      fail:
        msg: "keytool bulunamadı ({{ keytool_bin }}). Lütfen OpenJDK kurun."
      when: not keytool_stat.stat.exists

    ######################################################################
    # Java 17
    ######################################################################
    - name: Java 17 keystore var mı?
      stat:
        path: "{{ ks_java17 }}"
      register: j17_ks

    - name: (J17) Alias öncesinde var mı?
      command: >
        {{ keytool_bin }} -list -alias {{ cert_alias }}
        -keystore {{ ks_java17 }} -storepass {{ keystore_pass }}
      register: j17_before
      changed_when: false
      ignore_errors: true
      when: j17_ks.stat.exists

    - name: (J17) Import et (alias yoksa)
      command: >
        {{ keytool_bin }} -import -trustcacerts
        -keystore {{ ks_java17 }} -storepass {{ keystore_pass }}
        -noprompt -alias {{ cert_alias }} -file {{ cert_file }}
      register: j17_import
      when:
        - j17_ks.stat.exists
        - j17_before.rc is defined
        - j17_before.rc != 0

    - name: (J17) Son kontrol (detaylı liste)
      command: >
        {{ keytool_bin }} -v -list -keystore {{ ks_java17 }}
        -storepass {{ keystore_pass }} -alias {{ cert_alias }}
      register: j17_after
      changed_when: false
      ignore_errors: true
      when: j17_ks.stat.exists

    ######################################################################
    # Java 8
    ######################################################################
    - name: Java 8 keystore var mı?
      stat:
        path: "{{ ks_java8 }}"
      register: j8_ks

    - name: (J8) Alias öncesinde var mı?
      command: >
        {{ keytool_bin }} -list -alias {{ cert_alias }}
        -keystore {{ ks_java8 }} -storepass {{ keystore_pass }}
      register: j8_before
      changed_when: false
      ignore_errors: true
      when: j8_ks.stat.exists

    - name: (J8) Import et (alias yoksa)
      command: >
        {{ keytool_bin }} -import -trustcacerts
        -keystore {{ ks_java8 }} -storepass {{ keystore_pass }}
        -noprompt -alias {{ cert_alias }} -file {{ cert_file }}
      register: j8_import
      when:
        - j8_ks.stat.exists
        - j8_before.rc is defined
        - j8_before.rc != 0

    - name: (J8) Son kontrol (detaylı liste)
      command: >
        {{ keytool_bin }} -v -list -keystore {{ ks_java8 }}
        -storepass {{ keystore_pass }} -alias {{ cert_alias }}
      register: j8_after
      changed_when: false
      ignore_errors: true
      when: j8_ks.stat.exists

    ######################################################################
    # Özet
    ######################################################################
    - name: Özet (AWX output)
      debug:
        msg: |
          === Java Trust Store Özeti ===
          Host: {{ inventory_hostname }}

          Java 17 ({{ ks_java17 }}):
            - Keystore var mı?: {{ 'EVET' if j17_ks.stat.exists else 'HAYIR' }}
            {% if j17_ks.stat.exists %}
            - Öncesinde alias var mıydı?: {{ 'EVET' if (j17_before.rc|default(1)) == 0 else 'HAYIR' }}
            - Import yapıldı mı?: {% if (j17_before.rc|default(1)) != 0 %}{{ 'EVET' if (j17_import.rc|default(1)) == 0 else 'HATA' }}{% else %}GEREK YOK{% endif %}
            - Son durumda alias var mı?: {{ 'EVET' if (j17_after.rc|default(1)) == 0 else 'HAYIR' }}
            {% endif %}

          Java 8 ({{ ks_java8 }}):
            - Keystore var mı?: {{ 'EVET' if j8_ks.stat.exists else 'HAYIR' }}
            {% if j8_ks.stat.exists %}
            - Öncesinde alias var mıydı?: {{ 'EVET' if (j8_before.rc|default(1)) == 0 else 'HAYIR' }}
            - Import yapıldı mı?: {% if (j8_before.rc|default(1)) != 0 %}{{ 'EVET' if (j8_import.rc|default(1)) == 0 else 'HATA' }}{% else %}GEREK YOK{% endif %}
            - Son durumda alias var mı?: {{ 'EVET' if (j8_after.rc|default(1)) == 0 else 'HAYIR' }}
            {% endif %}
