---
- name: check-user-list
  hosts: all
  become: yes
  tasks:
    - name: check for ca_ybakir user
      shell: grep 'ca_ybakir' /etc/passwd
      register: display_output
      ignore_errors: yes

    - name: display_output
      debug:
        var: display_output.stdout_lines

    - name: save check-user-list output to file with timestamp
      copy:
        content: "{{ display_output.stdout | default('No matching user found.') }}"
        dest: "/tmp/awx_task_{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}.log"
