---
- name: check-process
  hosts: all
  become: yes
  tasks:
    - name: check-process
      command: "ps aux | grep manageengine"
      register: display_output

    - name: display_output
      debug:
        var: display_output.stdout_lines

    - name: save-check-process-output-to-file-with-timestamp
      copy:
        content: "{{ display_output.stdout }}"
        dest: "/tmp/awx_task_{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}.log"
