---
- name: FortiGate üzerinde admin kullanıcılarını listele
  hosts: all
  gather_facts: no
  tasks:
    - name: Admin kullanıcıları listele
      raw: show system admin | grep edit
      register: admin_output

    - name: Çıktıyı göster
      debug:
        var: admin_output.stdout_lines
