---
- name: FortiGate üzerinde SSH ile yeni kullanıcı oluştur
  hosts: all
  gather_facts: no
  tasks:
    - name: Yeni kullanıcı oluştur (SSH CLI üzerinden)
      ansible.builtin.raw: |
        config system admin
        edit yeniadmin
        set password GizliParola123
        set accprofile super_admin
        set vdom root
        set allowaccess ssh https
        next
        end
