---
- name: FortiGate list admin
  hosts: all
  gather_facts: no
  tasks:
    - name: show system admin | grep edit running
      ansible.builtin.shell: 'show system admin | grep edit'
      register: admin_list

    - name: Output list
      debug:
        var: admin_list.stdout_lines
