---
- name: FortiGate üzerinde yeni admin kullanıcısı oluştur
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    fortigate_host: "192.168.1.99"
    fortigate_token: "TOKENINIZ"  # veya kullanıcı/şifre ile login olabilir

  tasks:
    - name: Yeni admin kullanıcısı oluştur
      fortios_system_admin:
        vdom: "root"
        access_token: "{{ fortigate_token }}"
        host: "{{ fortigate_host }}"
        https: true
        state: "present"
        system_admin:
          name: "yeniadmin"
          password: "GizliParola123!"
          accprofile: "super_admin"  # veya read_only, custom vs.
          vdom:
            - "root"
          allowaccess: "https ssh"
