---
- name: FortiGate list admin users
  hosts: all
  gather_facts: no
  tasks:
    - name: FortiGate list admin users task
      raw: show system admin | grep edit
      register: admin_output

    - name: show output
      debug:
        var: admin_output.stdout_lines
