---
- name: FortiGate User Add
  hosts: all
  gather_facts: no
  tasks:
    - name: Create Nwe User
      ansible.builtin.raw: |
        config system admin
        edit test01
        set password Volcano7854
        set accprofile super_admin
        set vdom root
        set allowaccess ssh https
        next
        end
